### ISSUE TITLE
Error while "go get -u github.com/shurcooL/Go-Package-Store"

### ISSUE THREAD

**Issue by arvenil** [shurcooL/Go-Package-Store#26] opened 2014-11-27 10:15 UTC
Hi,

I just wanted to try out "Go-Package-Store" but it looks like it doesn't compile:

```sh
$ go get -u github.com/shurcooL/Go-Package-Store
# github.com/shurcooL/Go-Package-Store/presenter
src/github.com/shurcooL/Go-Package-Store/presenter/codegoogle.go:121: cannot use "github.com/sourcegraph/go-vcs/vcs".RemoteOpts literal (type "github.com/sourcegraph/go-vcs/vcs".RemoteOpts) as type "sourcegraph.com/sourcegraph/go-vcs/vcs".RemoteOpts in argument to r.(vcsclient.RepositoryCloneUpdater).CloneOrUpdate
src/github.com/shurcooL/Go-Package-Store/presenter/codegoogle.go:134: cannot use commitId (type "sourcegraph.com/sourcegraph/go-vcs/vcs".CommitID) as type "github.com/sourcegraph/go-vcs/vcs".CommitID in field value
src/github.com/shurcooL/Go-Package-Store/presenter/codegoogle.go:136: cannot assign []*"sourcegraph.com/sourcegraph/go-vcs/vcs".Commit to c.commits (type []*"github.com/sourcegraph/go-vcs/vcs".Commit) in multiple assignment
```

Any idea?

**Comment by suhyunjeon** [comment] 2015-01-20 08:04
Hello, I have a question.

I want to running "Go-Package-Store" but it looks like it doesn't work.

1. $ go get -u github.com/shurcooL/Go-Package-Store
2. $ go build
3. $ ./Go-Package-Store
4. opens a browser window automatically : http://localhost:7043/index.html
5. not found page (a browser)

How do I do? Please help me.

**Comment by shurcooL** [comment] 2015-01-20 08:40
Hi @suhyunjeon,

It looks like you're doing the right thing, so it should work.

When you run `Go-Package-Store`, is there any output?

I get:

```
$ Go-Package-Store
Using all Go packages in GOPATH.
Go Package Store server is running at http://localhost:7043/index.html.
GoPackages.Update: 655.519613 ms; 595 packages.
```

Do you see that?

**Comment by suhyunjeon** [comment] 2015-01-20 08:50
Thank you for your reply. 

I don't know exactly what it is.
So I removed the folder and create new gopath. And follow the command.
https://travis-ci.org/shurcooL/Go-Package-Store
```
1. $ go get -u github.com/shurcooL/Go-Package-Store  
2. $ go get golang.org/x/tools/cmd/vet
3. $ go get -t -v ./...
4. $ diff -u <(echo -n) <(gofmt -d ./)
5. $ go tool vet ./
6. $ go build  
7. $ ./Go-Package-Store
Using all Go packages in GOPATH.
(That's it)
8. opens a browser window automatically : http://localhost:7043/index.html  
9. Not found page (a browser)  
```

**Comment by shurcooL** [comment] 2015-01-20 08:53
Very interesting. Can you open a new issue please? What's the output of `go version`?

One thing about above, when you do `go get -u github.com/shurcooL/Go-Package-Store`, that installs the `Go-Package-Store` binary into `$GOPATH/bin`, but in step 7 you run `./Go-Package-Store`. Are you sure that's the right binary? Maybe you should be running `$GOPATH/bin/Go-Package-Store`?

**Comment by shurcooL** [comment] 2015-01-20 08:55
Ok, I have an idea what might be wrong. I'll need your output from `go version`. It might be that on your platform, when I run the command to open a browser window, it doesn't keep running the rest of the code. I can fix that, I just need to know more info about when it happens.

**Comment by suhyunjeon** [comment] 2015-01-20 08:56
```
$ go version
go version xgcc (Ubuntu 4.9.1-0ubuntu1) 4.9.1 linux/amd64
suhyunjeon@ubuntu-shjeon:~/gostore/gostore/bin$ ls
Go-Package-Store
suhyunjeon@ubuntu-shjeon:~/gostore/gostore/bin$ ./Go-Package-Store 
Using all Go packages in GOPATH.
```

It does not work. Same the work. T.T

**Comment by shurcooL** [comment] 2015-01-20 09:35
What version of Ubuntu are you running? Can you please also tell me the output of `xdg-open --version`?

**Comment by suhyunjeon** [comment] 2015-01-20 09:45
Thank you for your reply.

Can I check it tomorrow?
I am sorry I've left my office.

thank you.

2015년 1월 20일 화요일, Dmitri Shuralyov<notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>님이 작성한 메시지:

**Comment by shurcooL** [comment] 2015-01-20 09:46
Sure thing, no problem. We'll get this figured out so it will work. :) Thanks for your patience.

**Comment by suhyunjeon** [comment] 2015-01-20 23:57
Hello @shurcooL. Version is 1.0.2 like that.

```
$ xdg-open --version
xdg-open 1.0.2
```

**Comment by cryptix** [comment] 2015-01-21 00:17
May I suggest an vector to look into? I started seeing the same thing when one of my boxes got upgraded.

What started happening was that the browser tried to open the url before the listening socket was open. I checked with `lsof` to see if go-Package-Store was listening and it sure was. Entering the url again loads the page and changes begin to appear.

I never thought much of it until now.. @shurcooL: You might want to switch the open>listen around or wait for the socket to open first (if this is even the issue here but it sounds familiar..)

**Comment by shurcooL** [comment] 2015-01-21 03:04
@cryptix, you bring up a good point. There is definitely a race condition in the logic right now; it tries to open the browser and navigate to the URL first, and start the http server after. In practice it has always been okay for me because starting the http server is usually faster than starting a browser, but it's better not to have a race condition.

That said, it seems that @suhyunjeon's problem is elsewhere. @suhyunjeon says that it opens the browser at `http://localhost:7043/index.html` but only prints `Using all Go packages in GOPATH.`. If you look at the code,

```Go
// Open a browser tab and navigate to the main page.
u4.Open("http://" + *httpFlag + "/index.html")

fmt.Println("Go Package Store server is running at http://" + *httpFlag + "/index.html.")
```

Since the `Go Package Store server is running at ...` message is not being printed, that tells me that `Open` never returns.

`Open` is supposed to launch a new process (in this case, a browser that navigates to the specified URL) and return very quickly. I tried it on Ubuntu 14.04 with which had the same `xdg-open` version 1.0.2, and I couldn't reproduce the issue. But just to be safe (and likely to fix @suhyunjeon's problem), I'll want to move `Open` into a background goroutine so that it doesn't prevent the http server from starting if it blocks without returning.

I'll make a patch soon and ask you @suhyunjeon to try again.

**Comment by suhyunjeon** [comment] 2015-01-21 04:40
I figure out the problem.

It was very interesting.

As you guys know, when I run 'Go-Package-Store', they only open a browser and only print  like this.
```
Using all Go packages in GOPATH.
```

And!! I close the browser and after open a new browser (http://localhost:7043/index.html)
I can show the log 
```
Using all Go packages in GOPATH.
Go Package Store server is running at http://localhost:7043/index.html.
GoPackages.Update: 253.05100000000002 ms; 254 packages.
```

BUT they did not work. I got fatal error like this
```
suhyunjeon@ubuntu-shjeon:~/gopath/bin$ ./Go-Package-Store 
Using all Go packages in GOPATH.
Go Package Store server is running at http://localhost:7043/index.html.
GoPackages.Update: 253.05100000000002 ms; 254 packages.
unexpected fault address 0x7f0600000011
fatal error: fault
[signal 0xb code=0x1 addr=0x7f0600000011]

goroutine 388 [running]:

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

goroutine 1 [IO wait]:
main.main
	/home/suhyunjeon/gopath/src/github.com/shurcooL/Go-Package-Store/main.go:346

goroutine 5 [chan receive]:
main.updateWorker
	/home/suhyunjeon/gopath/src/github.com/shurcooL/Go-Package-Store/main.go:85
created by main.main
	/home/suhyunjeon/gopath/src/github.com/shurcooL/Go-Package-Store/main.go:339

goroutine 8 [chan receive]:
main.mainHandler
	/home/suhyunjeon/gopath/src/github.com/shurcooL/Go-Package-Store/main.go:235

goroutine 7 [finalizer wait]:

goroutine 12 [IO wait]:

goroutine 10 [chan receive]:
main.$nested0
	/home/suhyunjeon/gopath/src/github.com/shurcooL/Go-Package-Store/main.go:166
created by main.mainHandler
	/home/suhyunjeon/gopath/src/github.com/shurcooL/Go-Package-Store/main.go:165

goroutine 13 [IO wait]:

goroutine 14 [IO wait]:
golang.org_x_net_websocket.ReadByte.N49_golang.org_x_net_websocket.hybiFrameReaderFactory
	/home/suhyunjeon/gopath/src/golang.org/x/net/websocket/hybi.go:113
golang.org_x_net_websocket.NewFrameReader.N49_golang.org_x_net_websocket.hybiFrameReaderFactory
	/home/suhyunjeon/gopath/src/golang.org/x/net/websocket/hybi.go:126
golang.org_x_net_websocket.Read.pN31_golang.org_x_net_websocket.Conn
	/home/suhyunjeon/gopath/src/golang.org/x/net/websocket/websocket.go:176
main.openedHandler
	/home/suhyunjeon/gopath/src/github.com/shurcooL/Go-Package-Store/main.go:258
golang.org_x_net_websocket.serveWebSocket.N33_golang.org_x_net_websocket.Server
	/home/suhyunjeon/gopath/src/golang.org/x/net/websocket/server.go:90
golang.org_x_net_websocket.ServeHTTP.N34_golang.org_x_net_websocket.Handler
	/home/suhyunjeon/gopath/src/golang.org/x/net/websocket/server.go:113

goroutine 361 [semacquire]:
github.com_shurcooL_go_gists_gist7802150.MakeUpdated
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7802150/main.go:30
github.com_shurcooL_go_gists_gist7480523.UpdateVcsFields.pN50_github.com_shurcooL_go_gists_gist7480523.GoPackage
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7480523/main.go:88
main.$nested4
	/home/suhyunjeon/gopath/src/github.com/shurcooL/Go-Package-Store/main.go:225
gist7651991.$nested6
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7651991/main.go:104
created by gist7651991.$nested5
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7651991/main.go:96

goroutine 359 [chan send]:
main.$nested3
	/home/suhyunjeon/gopath/src/github.com/shurcooL/Go-Package-Store/main.go:217
created by main.mainHandler
	/home/suhyunjeon/gopath/src/github.com/shurcooL/Go-Package-Store/main.go:215

goroutine 394 [syscall]:
	goroutine in C code; stack unavailable

goroutine 363 [semacquire]:
github.com_shurcooL_go_gists_gist7802150.MakeUpdated
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7802150/main.go:30
github.com_shurcooL_go_gists_gist7480523.UpdateVcsFields.pN50_github.com_shurcooL_go_gists_gist7480523.GoPackage
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7480523/main.go:88
main.$nested4
	/home/suhyunjeon/gopath/src/github.com/shurcooL/Go-Package-Store/main.go:225
gist7651991.$nested6
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7651991/main.go:104
created by gist7651991.$nested5
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7651991/main.go:96

goroutine 366 [semacquire]:
github.com_shurcooL_go_gists_gist7802150.MakeUpdated
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7802150/main.go:30
github.com_shurcooL_go_gists_gist7480523.UpdateVcsFields.pN50_github.com_shurcooL_go_gists_gist7480523.GoPackage
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7480523/main.go:88
main.$nested4
	/home/suhyunjeon/gopath/src/github.com/shurcooL/Go-Package-Store/main.go:225
gist7651991.$nested6
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7651991/main.go:104
created by gist7651991.$nested5
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7651991/main.go:96

goroutine 368 [syscall]:
	goroutine in C code; stack unavailable
created by gist7651991.$nested5
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7651991/main.go:96

goroutine 367 [semacquire]:
github.com_shurcooL_go_gists_gist7802150.MakeUpdated
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7802150/main.go:30
github.com_shurcooL_go_gists_gist7480523.UpdateVcsFields.pN50_github.com_shurcooL_go_gists_gist7480523.GoPackage
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7480523/main.go:88
main.$nested4
	/home/suhyunjeon/gopath/src/github.com/shurcooL/Go-Package-Store/main.go:225
gist7651991.$nested6
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7651991/main.go:104
created by gist7651991.$nested5
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7651991/main.go:96

goroutine 365 [semacquire]:
github.com_shurcooL_go_gists_gist7802150.MakeUpdated
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7802150/main.go:30
github.com_shurcooL_go_gists_gist7480523.UpdateVcsFields.pN50_github.com_shurcooL_go_gists_gist7480523.GoPackage
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7480523/main.go:88
main.$nested4
	/home/suhyunjeon/gopath/src/github.com/shurcooL/Go-Package-Store/main.go:225
gist7651991.$nested6
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7651991/main.go:104
created by gist7651991.$nested5
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7651991/main.go:96

goroutine 360 [semacquire]:
gist7651991.$nested5
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7651991/main.go:112
created by github.com_shurcooL_go_gists_gist7651991.GoReduce
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7651991/main.go:89

goroutine 364 [select]:
vcs.httpGET
	/home/suhyunjeon/gopath/src/golang.org/x/tools/go/vcs/http.go:22
vcs.googleCodeVCS
	/home/suhyunjeon/gopath/src/golang.org/x/tools/go/vcs/vcs.go:680
golang.org_x_tools_go_vcs.RepoRootForImportPathStatic
	/home/suhyunjeon/gopath/src/golang.org/x/tools/go/vcs/vcs.go:448
golang.org_x_tools_go_vcs.RepoRootForImportPath
	/home/suhyunjeon/gopath/src/golang.org/x/tools/go/vcs/vcs.go:383
github.com_shurcooL_go_gists_gist7480523.UpdateVcsFields.pN50_github.com_shurcooL_go_gists_gist7480523.GoPackage
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7480523/main.go:92
main.$nested4
	/home/suhyunjeon/gopath/src/github.com/shurcooL/Go-Package-Store/main.go:225
gist7651991.$nested6
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7651991/main.go:104
created by gist7651991.$nested5
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7651991/main.go:96

goroutine 362 [semacquire]:
github.com_shurcooL_go_gists_gist7802150.MakeUpdated
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7802150/main.go:30
github.com_shurcooL_go_gists_gist7480523.UpdateVcsFields.pN50_github.com_shurcooL_go_gists_gist7480523.GoPackage
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7480523/main.go:88
main.$nested4
	/home/suhyunjeon/gopath/src/github.com/shurcooL/Go-Package-Store/main.go:225
gist7651991.$nested6
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7651991/main.go:104
created by gist7651991.$nested5
	/home/suhyunjeon/gopath/src/github.com/shurcooL/go/gists/gist7651991/main.go:96

```

OMG.

**Comment by shurcooL** [comment] 2015-01-21 05:04
> As you guys know, when I run 'Go-Package-Store', they only open a browser and only print  like this.
> ```
> Using all Go packages in GOPATH.
> ```
> 
> And!! I close the browser and after open a new browser (http://localhost:7043/index.html)
> I can show the log 
> ```
> Using all Go packages in GOPATH.
> Go Package Store server is running at http://localhost:7043/index.html.
> GoPackages.Update: 253.05100000000002 ms; 254 packages.
> ```

Yes, that confirms what I suspected, that `Open` does not return for you until the browser (the process that was started)` exists. My upcoming fix will fix that.

> BUT they did not work. The browser show the alert(Go Package Store server disconnected).
> I got fatal error

Hmm, I think it may be an unrelated issue. I have seen something like that one time out of 100+ runs, so there may still be some edge cases that I need to handle more carefully. But I'll fix it one step at a time.

@suhyunjeon, just so I have a better idea, can you tell me the exact name/versions of:

- Your OS.
- The browser that was being automatically started.
- `git --version`

Thanks!

**Comment by shurcooL** [comment] 2015-01-21 05:26
@suhyunjeon, I've just pushed a15fc561fd6d4e10f65506b3842dba7799fa4b70 which should fix your issue with starting correctly.

Can you try updating via `go get -u github.com/shurcooL/Go-Package-Store` and try again?

**Comment by suhyunjeon** [comment] 2015-01-21 07:23
I tried to update source code. BUT it also did not work. Connected url to 'http://localhost:7043/index.html'. I can see the UI(Checking for updates...)
Disconnected go package store server. 

1. $ go get -u github.com/shurcooL/Go-Package-Store
2. $ go build
3. $ ./Go-Package-Store
4. opens a browser window automatically : http://localhost:7043/index.html
5. disconnected go package store server.

I will change golang version soon. And I will try again.
Thank you.

**Comment by shurcooL** [comment] 2015-01-23 05:25
That is unfortunate; it should work. :( I'm running out of ideas for what you can try. But you still haven't told me what OS and browser you're using.

I can suggest trying to update to latest official stable version of Go, which is currently 1.4.1, and is available at http://golang.org/doc/install. Then update again using `go get -u github.com/shurcooL/Go-Package-Store` and run `$GOPATH/bin/Go-Package-Store`. It's not needed to do `go build` after `go get -u`, since `go get -u` will also do `go install`. That puts a built `Go-Package-Store` binary in your `$GOPATH/bin` folder.

**Comment by shurcooL** [comment] 2015-02-08 05:48
@suhyunjeon, have you had better luck after updating Go?

**Comment by suhyunjeon** [comment] 2015-02-09 01:40
Hello Dmitri!

I upgrade go version to go1.4.1.linux-amd64.tar.gz
<https://storage.googleapis.com/golang/go1.4.1.linux-amd64.tar.gz> (
https://golang.org/dl/)

1. *go get -u github.com/shurcooL/Go-Package-Store
<http://github.com/shurcooL/Go-Package-Store>*

2. set *$GOPATH/bin* from *~/.profile* in ubuntu

3. run *$GOPATH/bin/Go-Package-Store*
@ubuntu-shjeon:~/gocode/bin$ ./Go-Package-Store
Using all Go packages in GOPATH.
Go Package Store server is
 running at http://localhost:7043/index.html.
GoPackages.Update: 297.45500000000004 ms; 179 packages.

4. A browser iss opening automatically. (http://localhost:7043/index.html)

And then there is no anything. (I have many gopath in my $HOME).
Updates
No Updates Available


T.T

2015-02-08 14:48 GMT+09:00 Dmitri Shuralyov <notifications@github.com>:

**Comment by shurcooL** [comment] 2015-02-09 02:04
That sounds like an improvement, it's not crashing anymore.

Seeing "No Updates Available" is normal behavior, and it means one of two things:

1. It's possible you already have all latest versions; there are indeed no updates available. Try running Go Package Store at a later time, perhaps something will come up by then.

   I see that you only have 179 packages in your GOPATH. That's not a lot, so this is a possibility, especially since you've recently updated Go and likely got all new packages at that time.

2. It's possible Go-Package-Store cannot _detect_ any packages it can update. It only presents updates for packages that have a clean working directly, and a correct remote that matches the import path.

**Comment by suhyunjeon** [comment] 2015-02-09 02:43
Thank you for your reply.

I got it. I downloaded some go source from github.(go get "blah blah blah")
And then run *'./bin/Go-Package-Store'*. It did not work like this. I will
check the source code.

------------------------------------------------------------------------------------------------------------------------------------
ubuntu-shjeon:~/gocode$* ./bin/Go-Package-Store *
Using all Go packages in GOPATH.
Go Package Store server is running at http://localhost:7043/index.html.
*GoPackages.Update: 207.251 ms; 211 packages.*

*unexpected fault address 0x7f3900000011fatal error: fault*
[signal 0xb code=0x1 addr=0x7f3900000011]

goroutine 362 [running]:

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0


goroutine 1 [IO wait]:
main.main
    ${GOPATH}/src/github.com/shurcooL/Go-Package-Store/main.go:364

goroutine 14 [IO wait]:
golang.org_x_net_websocket.ReadByte.N49_golang.org_x_net_websocket.hybiFrameReaderFactory
    ${GOPATH}/src/golang.org/x/net/websocket/hybi.go:113
golang.org_x_net_websocket.NewFrameReader.N49_golang.org_x_net_websocket.hybiFrameReaderFactory
   ${GOPATH}/src/golang.org/x/net/websocket/hybi.go:126
golang.org_x_net_websocket.Read.pN31_golang.org_x_net_websocket.Conn
    ${GOPATH}/src/golang.org/x/net/websocket/websocket.go:176
main.openedHandler
    ${GOPATH}/src/github.com/shurcooL/Go-Package-Store/main.go:270
golang.org_x_net_websocket.serveWebSocket.N33_golang.org_x_net_websocket.Server
    ${GOPATH}/src/golang.org/x/net/websocket/server.go:90
golang.org_x_net_websocket.ServeHTTP.N34_golang.org_x_net_websocket.Handler
    ${GOPATH}/src/golang.org/x/net/websocket/server.go:113

goroutine 5 [chan receive]:
main.updateWorker
    ${GOPATH}/src/github.com/shurcooL/Go-Package-Store/main.go:97
created by main.main
   ${GOPATH}/src/github.com/shurcooL/Go-Package-Store/main.go:351

goroutine 7 [chan receive]:
main.mainHandler
    ${GOPATH}/src/github.com/shurcooL/Go-Package-Store/main.go:247

goroutine 8 [IO wait]:

goroutine 9 [IO wait]:

goroutine 13 [IO wait]:

goroutine 11 [chan receive]:
main.$nested0
    ${GOPATH}src/github.com/shurcooL/Go-Package-Store/main.go:178
created by main.mainHandler
   ${GOPATH}/github.com/shurcooL/Go-Package-Store/main.go:177

goroutine 15 [finalizer wait]:

goroutine 315 [select]:
vcs.$nested0
    ${GOPATH}/src/golang.org/x/tools/go/vcs/http.go:50
vcs.httpsOrHTTP
    ${GOPATH}/src/golang.org/x/tools/go/vcs/http.go:58
golang.org_x_tools_go_vcs.RepoRootForImportDynamic
    ${GOPATH}/src/golang.org/x/tools/go/vcs/vcs.go:491
golang.org_x_tools_go_vcs.RepoRootForImportPath
    ${GOPATH}/src/golang.org/x/tools/go/vcs/vcs.go:385
github.com_shurcooL_go_gists_gist7480523.UpdateVcsFields.pN50_github.com_shurcooL_go_gists_gist7480523.GoPackage
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7480523/main.go:92
main.$nested4
    ${GOPATH}/src/github.com/shurcooL/Go-Package-Store/main.go:237
gist7651991.$nested6
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7651991/main.go:104
created by gist7651991.$nested5
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7651991/main.go:96

goroutine 314 [semacquire]:
github.com_shurcooL_go_gists_gist7802150.MakeUpdated
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7802150/main.go:30
github.com_shurcooL_go_gists_gist7480523.UpdateVcsFields.pN50_github.com_shurcooL_go_gists_gist7480523.GoPackage
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7480523/main.go:88
main.$nested4
    ${GOPATH}/github.com/shurcooL/Go-Package-Store/main.go:237
gist7651991.$nested6
    ${GOPATH}/github.com/shurcooL/go/gists/gist7651991/main.go:104
created by gist7651991.$nested5
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7651991/main.go:96

goroutine 313 [semacquire]:
github.com_shurcooL_go_gists_gist7802150.MakeUpdated
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7802150/main.go:30
github.com_shurcooL_go_gists_gist7480523.UpdateVcsFields.pN50_github.com_shurcooL_go_gists_gist7480523.GoPackage
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7480523/main.go:88
main.$nested4
    ${GOPATH}/src/github.com/shurcooL/Go-Package-Store/main.go:237
gist7651991.$nested6
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7651991/main.go:104
created by gist7651991.$nested5
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7651991/main.go:96

goroutine 312 [semacquire]:
github.com_shurcooL_go_gists_gist7802150.MakeUpdated
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7802150/main.go:30
github.com_shurcooL_go_gists_gist7480523.UpdateVcsFields.pN50_github.com_shurcooL_go_gists_gist7480523.GoPackage
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7480523/main.go:88
main.$nested4
    ${GOPATH}/src/github.com/shurcooL/Go-Package-Store/main.go:237
gist7651991.$nested6
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7651991/main.go:104
created by gist7651991.$nested5
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7651991/main.go:96

goroutine 310 [chan send]:
main.$nested3
    ${GOPATH}/src/github.com/shurcooL/Go-Package-Store/main.go:229
created by main.mainHandler
    ${GOPATH}/src/github.com/shurcooL/Go-Package-Store/main.go:227

goroutine 311 [semacquire]:
gist7651991.$nested5
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7651991/main.go:112
created by github.com_shurcooL_go_gists_gist7651991.GoReduce
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7651991/main.go:89

goroutine 368 [syscall]:
    goroutine in C code; stack unavailable

goroutine 319 [semacquire]:
github.com_shurcooL_go_gists_gist7802150.MakeUpdated
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7802150/main.go:30
github.com_shurcooL_go_gists_gist7480523.UpdateVcsFields.pN50_github.com_shurcooL_go_gists_gist7480523.GoPackage
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7480523/main.go:88
main.$nested4
    ${GOPATH}/src/github.com/shurcooL/Go-Package-Store/main.go:237
gist7651991.$nested6
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7651991/main.go:104
created by gist7651991.$nested5
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7651991/main.go:96

goroutine 318 [semacquire]:
github.com_shurcooL_go_gists_gist7802150.MakeUpdated
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7802150/main.go:30
github.com_shurcooL_go_gists_gist7480523.UpdateVcsFields.pN50_github.com_shurcooL_go_gists_gist7480523.GoPackage
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7480523/main.go:88
main.$nested4
    ${GOPATH}/src/github.com/shurcooL/Go-Package-Store/main.go:237
gist7651991.$nested6
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7651991/main.go:104
created by gist7651991.$nested5
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7651991/main.go:96

goroutine 317 [syscall]:
    goroutine in C code; stack unavailable
created by gist7651991.$nested5
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7651991/main.go:96

goroutine 316 [semacquire]:
github.com_shurcooL_go_gists_gist7802150.MakeUpdated
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7802150/main.go:30
github.com_shurcooL_go_gists_gist7480523.UpdateVcsFields.pN50_github.com_shurcooL_go_gists_gist7480523.GoPackage
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7480523/main.go:88
main.$nested4
    ${GOPATH}/src/github.com/shurcooL/Go-Package-Store/main.go:237
gist7651991.$nested6
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7651991/main.go:104
created by gist7651991.$nested5
    ${GOPATH}/src/github.com/shurcooL/go/gists/gist7651991/main.go:96

EOF


2015-02-09 11:04 GMT+09:00 Dmitri Shuralyov <notifications@github.com>:

**Comment by shurcooL** [comment] 2015-03-14 01:00
@suhyunjeon, is there anything else I can do to help?

If not, do you mind if I close this issue?

**Comment by suhyunjeon** [comment] 2015-04-11 09:00
Hello, I am sorry to late for reply.

It did work exactly. Close my issue.
Thank you.

Have a nice day!

2015년 3월 14일 토요일, Dmitri Shuralyov<notifications@github.com>님이 작성한 메시지:

**Comment by shurcooL** [comment] 2015-04-11 16:05
I'm glad to hear it works now! Thanks for letting me know.

If you run into anything else, feel free to open a new issue.

**Closed by shurcooL** 2015-04-11 16:05 UTC
