### ISSUE TITLE
Silently ignores updates if the tree is dirty

### ISSUE THREAD

**Issue by mvdan** [shurcooL/Go-Package-Store#64] opened 2017-01-10 09:38 UTC
If there are unstaged changes, git may refuse to pull changes from the remote. This is expected and natural.

However, (presumably) due to this, Go-Package-Store has kept my `x/tools` repo at the state of mid-November. I made a slight change to `cmd/stringer` back then and left it unstaged. I just ran a `git pull` manually after cleaning it up and indeed I'm back on the real master.

I suggest that the tool should be more verbose about this. I'm betting other repos in my `GOPATH` are suffering from similar issues without me noticing. I'll only notice months after, once one of my repos is so old that things start to break (like they just did now with `x/tools`).

**Comment by shurcooL** [comment] 2017-01-10 16:45
Valid issue, but duplicate of #58. I'll link it there.

**Closed by shurcooL** 2017-01-10 16:45 UTC
Labels: duplicate
